---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2 webserver
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"
  - name: i want to install apache2 webserver
    apt:
      name: apache2
      state: absent
    when: ansible_os_family =="Debian"
