---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2 webserver
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to install apache2 webservice
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"

  - name: i want to install my httpd webserver on amazonnode
    dnf:
      name: httpd
      state: present
    when: ansible_os_family"== "RedHat"
  
  - name: i want to install my httpd webservice on amaxzon
    dnf:
      name: httpd
      state: started
    when: ansible_os_family"== "RedHat"
